#!/bin/sh
# shellcheck disable=SC2046

VERSION="0.4"
CONF="${XDG_CONFIG_HOME:-$HOME/.config}/quand/config"

language="${LANG:-en_US.UTF-8}"
calendar="${XDG_DATA_HOME:-$HOME/.local/share}/quand/calendar"
editor="${EDITOR:-vi}"
header=1
past=-1
future=14
yesterday="yesterday  "
today="\033[1mtoday      "
tomorrow="tomorrow   "
special="special   "
spaces="        "
mondayfirst=0

getdate() {
	LC_ALL="$language" date --date="$1 day" "+%Y@%m@%d@%a$spaces"
}

split() {
	set -f
	old_ifs=$IFS
	IFS=@
	# shellcheck disable=SC2086
	set -- $1
	printf '%s\n' "$@"
	IFS=$old_ifs
	set +f
}

printspecial() {
	for line in $calendar; do
		case $line in
		"* * *"*)
			printf "$special\033[m%s\n" "${line#"* * *"}" ;;
		esac
	done
}

print() {
	for line in $calendar; do
		case $line in
		"$1 $2 $3"*)
			printf "${5:-$4}\033[m%s\n" "$line" ;;
		"* $2 $3"*)
			printf "${5:-$4}\033[m%s\n" "$1${line#"*"}" ;;
		"* * $3"*)
			printf "${5:-$4}\033[m%s\n" "$1 $2${line#"* *"}" ;;
		"${4%"$spaces"}"*)
			printf "${5:-$4}\033[m%s\n"\
				"$1 $2 $3${line#"${4%"$spaces"}"}" ;;
		esac
	done
}

calendar() {
	if [ "$mondayfirst" -eq 1 ]; then
		LC_ALL="$language" cal -m -n "${1:-1}"
	else
		LC_ALL="$language" cal -s -n "${1:-1}"
	fi
}

args() {
	while [ -n "$*" ]; do
		[ -z "$2" ] &&
			printf '\033[31mError:\033[m no argument given\n' 1>&2 &&
			usage &&
			exit 1
		case $1 in
		-c|--calendar)
			calendar="$2" ;;
		-p|--past)
			[ "$2" -gt 0 ] &&
				printf "\033[33mHint:\033[m 'past' is negative.\n\n"
			past="$2" ;;
		-f|--future)
			future="$2" ;;
		*)
			printf '\033[31mError:\033[m unknown option %s\n' "$*" 1>&2
			usage
			exit 1 ;;
		esac
		shift 2
	done
}

usage() {
	printf 'Usage: %s [options]

Options:
no option             | Default
-h|--help             │ Print this help message and exit
-v|--version          | Print the version
-c|--calendar [path]  | Temporarily change the calendar file used
-p|--past [n]         | Temporarily change past (n is negative)
-f|--future [n]       | Temporarily change future (n is positive)
                      |
e|edit                | Edit the calendar file
c|cal [n]             | Print a calendar with 1 or n months

Have a look at the README for more information about the configuration.\n'\
	"${0##*/}" 1>&2
}

main() {
	[ -f "$CONF" ] && . "$CONF"

	case $1 in
	-v|--version)
		printf '%s %s\n' "${0##*/}" "$VERSION" 1>&2
		return 0 ;;
	-h|--help)
		usage
		return 0 ;;
	e|edit)
		"$editor" "$calendar"
		return ;;
	c|cal)
		calendar "$2"
		return ;;
	-*)
		args "$@"
		exec ;;
	'')
		exec ;;
	*)
		printf '\033[31mError:\033[m unknown option %s\n' "$*" 1>&2
		usage
		return 1 ;;
	esac

	[ ! -f "$calendar" ] &&
		printf '\033[31mError:\033[m %s is not a valid file\n' "$calendar" 1>&2 &&
		return 1

	calendar="$(sort "$calendar")"
	IFS=$(printf '\n\b')

	[ "$header" = 1 ] && printf '%s\n\n' "$(LC_ALL="$language" date)"

	while [ "$past" -lt -1 ]; do
		print $(split "$(getdate "$past")")
		past=$((past+1))
	done

	[ "$past" -eq -1 ] && print $(split "$(getdate "-1")") "$yesterday"

	print $(split "$(getdate 0)") "$today"

	[ "$future" -ge 1 ] && print $(split "$(getdate "+1")") "$tomorrow"

	cpt=2
	while [ "$future" -gt 1 ]; do
		print $(split "$(getdate "+$cpt")")
		future="$((future-1))"
		cpt="$((cpt+1))"
	done

	printspecial
}

main "$@"
