.Dd April 14, 2023
.Dt QUAND 1
.Sh NAME
.Nm quand
.Nd simple calendar
.Sh SYNOPSIS
.Nm
.Op OPTIONS
.Sh DESCRIPTION
.Nm
is a simple calendar for the command line.
.Pp
.Sh OPTIONS
.Bl -tag -width Ds
.It e, edit
Edit the calendar file.
.It c, cal Op Ar n
Print a calendar with 1 or
.Ar n
months.
.It Fl c , -calendar Ar path
Temporarily change the calendar file used.
.It Fl d , -date Ar date
Print events for a specific date with this format: YYYY/MM/DD.
.It Fl p , -past Ar n
Temporarily change past (n is negative).
.It Fl f , -future Ar n
Temporarily change future (n is positive).
.It Fl h , -help
Print an help message to stderr and exit.
.It Fl v , -version
Print version information to stderr and exit.
.El
.Sh CONFIGURATION
$XDG_CONFIG_HOME/quand/config
.Nd
Default config file. If XDG_CONFIG_HOME is not set, $HOME/.config/ is used.
.Pp
Default configuration:
 language=en_US.UTF-8
 calendar=/home/username/.local/share/quand/calendar
 editor=vi
 header=1
 past=-1
 future=14
 yesterday="yesterday  "
 today="\\033[1mtoday      "
 tomorrow="tomorrow   "
 special="special   "
 spaces="        "
 mondayfirst=0
.Sh EXAMPLE
$XDG_DATA_HOME/quand/calendar
.Nd
Default calendar file. If XDG_DATA_HOME is not set, $HOME/.local/share is used.
.Pp
Example of calendar file:
 # Don't forget the 0 behind month or day
 2023 04 28, 07:30 -> 09:30 English
 2023 03 12, Dentist

 # For events that happen once a week:
 # The name of each day depends on your locale
 Mon, don't forget to update with emerge -uDN @world
 Fri, it's friday!

 # Use a star for events that happen once a year:
 * 08 10, Mum's anniversary
 * 07 14, Bastille Day

 # Use 2 stars for events that happen once a month:
 * * 01, Happy New Month!

 # Use 3 stars to always show an event:
 * * * Good Morning :)
 * * * 2023 03 31, URGENT don't forget your meeting
